language: node_js
node_js:
  - "lts/*"
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
install:
  - pnpm install
services:
  - docker
jobs:
  include:
    - stage: "Tests"
      name: "Unit tests"
      script: pnpm run test
    - name: "Submit test coverage"
      script: pnpm run test:coverage
    - name: "Lint"
      script: pnpm run lint
    - name: "Integration tests"
      script: pnpm start
    - stage: "Deploy"
      name: "Semantic Release"
      script:
        - docker build -t dicediscord/bot .
        - pnpx semantic-release
